---
  parser: '@typescript-eslint/parser'
  extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  plugins:
  - prettier
  - '@typescript-eslint'
  parserOptions:
    sourceType: module
    ecmaVersion: 2018
  env:
    es6: true
    node: true
  rules:
    semi:
    - 'error'
    - 'always'
    no-unused-vars: 2
    no-undef: 2
    no-var: 2
    prettier/prettier:
    - error
    - trailingComma: 'es5'
      singleQuote: true
